### ISSUE TITLE
show ghosts when watching replay

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-autohide-opponents#1]
Since Nadeo broke/disabled keyboard actions while watching a replay, I think having ghosts automatically enabled with this plugin would be helpful. Currently it's: click record (or multiple) to watch it -> realize ghosts are off -> go out of replay to enable ghosts -> finally click record again to watch with ghosts

If it helps, detecting a replay being watched is currently like so (at least what I've found):
`App.Network.ServerInfo.CurGameModeStr` ends with `_Local`
`App.CurrentPlayground.UIConfigs[0].UISequence` is `CGamePlaygroundUIConfig::EUISequence::UIInteraction`
`App.PlaygroundScript` is not `null`

**Comment by XertroV** [comment]
You should be able to test this by using the debug tab in plugin settings.

I think UIInteraction might be used in other places (in solo) but not sure. 
There are some other ways to detect watching a ghost, too, like the ghost vehicle vis ent ID is set at an offset in the GameTerminal.

I can probably add something

**Comment by ezio416** [comment]
Can confirm, toggling ghosts in the plugin settings works while watching a replay. I haven't seen UIInteraction used elsewhere (in combination with the local gamemode and null playground script), but then again I don't always have a window open showing the current sequence.

UIInteraction is also used between rounds in COTD, Royal, and Hotseat, but we can't watch replays in those modes so that shouldn't matter.

**Comment by XertroV** [comment]
Since this is fixed in the latest game update, I'll close the issue as not required.
